trigger:
- azure-pipelines

pool:
  vmImage: ubuntu-latest
  
variables:
  BUILD_CONFIGURATION: Release
  IMAGE_NAME: hannakasai002/scheduler-slack
  FINAL_IMAGE_TAG: latest

steps:
- task: Docker@2
  displayName: Log into a docker registry
  inputs:
    containerRegistry: 'docker-hub'
    command: 'login'
    addPipelineData: false
    addBaseImageData: false

- task: Docker@2
  displayName: Create a base image
  inputs:
    containerRegistry: 'docker-hub'
    repository: 'hannakasai002/scheduler-slack'
    command: 'build'
    arguments: '--progress=plain --no-cache -t $(IMAGE_NAME)'
    Dockerfile: '**/base.Dockerfile'
    buildContext: './Scheduler.Bot'
    tags: 'base'
    addPipelineData: false
    addBaseImageData: false

- task: Docker@2
  displayName: Restore dependencies
  inputs:
    containerRegistry: 'docker-hub'
    repository: 'hannakasai002/scheduler-slack'
    command: 'build'
    arguments: '--progress=plain --no-cache -t $(IMAGE_NAME)'
    Dockerfile: '**/restore.Dockerfile'
    buildContext: './Scheduler.Bot'
    tags: 'restore'
    addPipelineData: false
    addBaseImageData: false

- task: Docker@2
  displayName: Build the solution
  inputs:
    containerRegistry: 'docker-hub'
    repository: 'hannakasai002/scheduler-slack'
    command: 'build'
    arguments: '--progress=plain --no-cache -t $(IMAGE_NAME) --build-arg BUILD_CONFIGURATION --build-arg IMAGE_NAME'
    Dockerfile: '**/build.Dockerfile'
    buildContext: './Scheduler.Bot'
    tags: 'build'
    addPipelineData: false
    addBaseImageData: false

- task: Docker@2
  displayName: Publish the API
  inputs:
    containerRegistry: 'docker-hub'
    repository: 'hannakasai002/scheduler-slack'
    command: 'build'
    arguments: '--progress=plain --no-cache -t $(IMAGE_NAME) --build-arg IMAGE_NAME --build-arg BUILD_CONFIGURATION=$(BUILD_CONFIGURATION)'
    Dockerfile: '**/publish.Dockerfile'
    buildContext: './Scheduler.Bot'
    tags: 'publish'
    addPipelineData: false
    addBaseImageData: false

- task: Docker@2
  displayName: Pull the image to the dockerhub
  inputs:
    containerRegistry: 'docker-hub'
    repository: 'hannakasai002/scheduler-slack'
    command: 'buildAndPush'
    arguments: '--progress=plain --no-cache -t $(IMAGE_NAME) --build-arg IMAGE_NAME'
    Dockerfile: '**/final.Dockerfile'
    buildContext: './Scheduler.Bot'
    tags: '$(FINAL_IMAGE_TAG)'
    addPipelineData: false
    addBaseImageData: false