trigger:
- main

pool:
  vmImage: ubuntu-latest
  
variables:
  BUILD_CONFIGURATION: Release
  IMAGE_NAME: scheduler-slack
  FINAL_IMAGE_TAG: latest

steps:
- task: Docker@2
  displayName: Log into a docker registry
  inputs:
    containerRegistry: 'docker-hub'
    command: 'login'
    addPipelineData: false
    addBaseImageData: false

- task: Docker@2
  displayName: Crete base image
  inputs:
    containerRegistry: 'docker-hub'
    repository: 'hannakasai002/scheduler-slack'
    command: 'build'
    arguments: '--target base'
    Dockerfile: '**/base.Dockerfile'
    buildContext: './Scheduler.Bot'
    tags: '$(IMAGE_NAME):base'
    addPipelineData: false
    addBaseImageData: false

- task: Docker@2
  displayName: Restore
  inputs:
    containerRegistry: 'docker-hub'
    repository: 'hannakasai002/scheduler-slack'
    command: 'build'
    arguments: '--target restore --build-arg BUILD_CONFIGURATION'
    Dockerfile: '**/restore.Dockerfile'
    buildContext: './Scheduler.Bot'
    tags: '$(IMAGE_NAME):restore'
    addPipelineData: false
    addBaseImageData: false

- task: Docker@2
  displayName: Build
  inputs:
    containerRegistry: 'docker-hub'
    repository: 'hannakasai002/scheduler-slack'
    command: 'build'
    arguments: '--target build --build-arg BUILD_CONFIGURATION --build-arg CONTAINER_NAME'
    Dockerfile: '**/build.Dockerfile'
    buildContext: './Scheduler.Bot'
    tags: '$(IMAGE_NAME):build'
    addPipelineData: false
    addBaseImageData: false

- task: Docker@2
  displayName: Publish
  inputs:
    containerRegistry: 'docker-hub'
    repository: 'hannakasai002/scheduler-slack'
    command: 'build'
    arguments: '--target publish --build-arg CONTAINER_NAME'
    Dockerfile: '**/publish.Dockerfile'
    buildContext: './Scheduler.Bot'
    tags: '$(IMAGE_NAME):publish'
    addPipelineData: false
    addBaseImageData: false

- task: Docker@2
  inputs:
    containerRegistry: 'docker-hub'
    repository: 'hannakasai002/scheduler-slack'
    command: 'buildAndPush'
    arguments: '--target final --build-arg CONTAINER_NAME'
    Dockerfile: '**/final.Dockerfile'
    buildContext: './Scheduler.Bot'
    tags: '$(IMAGE_NAME):$(FINAL_IMAGE_TAG)'
    addPipelineData: false
    addBaseImageData: false